application:
  name: ${rootProject.name}
  version: ${version}
logging:
  file:
    name: ${rootProject.name}.log
    path:
  logback:
    rollingpolicy:
      #      file-name-pattern:
      clean-history-on-start: false
      max-file-size: 10MB
      total-size-cap: 20GB
      max-history: 30
  level:
    root: info
    io.github.syakuis: trace
    org.springframework.web: info
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: off
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: off
server:
  port: 8080
#  forward-headers-strategy: native
#  tomcat:
#    port-header: X-Forwarded-Port
#    remote-ip-header: X-Forwarded-For
#    protocol-header: X-Forwarded-Proto
#    accesslog:
#      directory:
#      enabled: false
#      file-date-format: .yyyy-MM-dd
spring:
  main:
    banner-mode: console
  messages:
    basename: i18n/message
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: never
    schema: classpath:schema/schema.sql
    data: classpath:schema/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true